basePath: /
definitions:
  static.Response:
    properties:
      data:
        type: object
      message:
        type: string
    type: object
host: liangjun.work
info:
  contact:
    name: wuzehui
  description: ginframework项目
  title: ginframework项目
  version: "1.0"
paths:
  /:
    get:
      description: 测试
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/static.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/static.Response'
      tags:
      - 测试
swagger: "2.0"
